version: 0.2

phases:
  pre_build:
    commands:
      - echo Pull loadimpact/k6 image..
      - docker pull loadimpact/k6
  build:
    commands:
      - echo Run performance test
      # - docker run -i loadimpact/k6 run - <performance/100VUs/perf_SearchEndpoint.js -e BASE_URL=https://pro.missiongraph.io -e AUTH_KEY=lotcp4aswl7qztahdpbt5l7zy -e AUTH_USER=MGtestuser
      - docker run -v "`pwd`/k6Test":/mounted -i loadimpact/k6 run <mounted/performance/100VUs/perf_ReportingEndpoint.js -e BASE_URL=https://pro.missiongraph.io -e AUTH_KEY=lotcp4aswl7qztahdpbt5l7zy -e AUTH_USER=MGtestuser
  post_build:
    commands:
        - echo Performance test complete