version: 0.2

phases:
  pre_build:
    commands:
      - echo Pull loadimpact/k6 image..
      - docker pull loadimpact/k6
  build:
    commands:
      - echo Run performance test
      - docker run -i loadimpact/k6 run - <performance/100VUs/perf_SearchEndpoint.js
  post_build:
    commands:
        - echo Performance test complete