version: 0.2

phases:
  pre_build:
    commands:
      - echo Pull loadimpact/k6 image..
      - docker pull loadimpact/k6
  build:
    commands:
      - echo Run performance test
      # - docker run -i loadimpact/k6 run - <performance/100VUs/perf_SearchEndpoint.js -e BASE_URL=https://pro.missiongraph.io -e AUTH_KEY=lotcp4aswl7qztahdpbt5l7zy -e AUTH_USER=MGtestuser
      - echo $pwd
      - docker.image("${build.imageName}").inside("-v $pwd:/app") {
                    sh "ls -l /app/"
                    sh "chmod +rwx ./"
                    sh "chmod +x uitest_helpers/driver/driver_executables/**/*"
                    sh "${testCmd}"
                }
      - docker run -v $(pwd)/k6Test:/mounted -i loadimpact/k6:latest run /mounted/performance/100VUs/perf_SearchEndpoint.js -e BASE_URL=https://pro.missiongraph.io -e AUTH_KEY=lotcp4aswl7qztahdpbt5l7zy -e AUTH_USER=MGtestuser
  post_build:
    commands:
        - echo Performance test complete